import type { Club } from "@/store/schemas/club.schema";
import type { User, UserTable } from "@/store/schemas/user.schema";

export const mockUsers: UserTable[] = [
    {
      id: "user_001",
      name: "John Smith",
      email: "john.smith@example.com",
      password: "hashed_password_123",
      emailVerified: true,
      identityVerified: true,
      teamId: "team_alpha",
      fanSince: new Date("2022-03-15"),
      squadNumber: 7,
      username: "johnsmith07",
      oauthProvider: "google",
      refreshTokenVersion: 1,
      createdAt: new Date("2022-03-15T10:30:00Z"),
      updatedAt: new Date("2024-12-20T14:22:00Z"),
      inviteCode: "JS7XM2K9",
      inviteCodeUsed: "AB3KL8NP",
      coin: "12"
    },
    {
      id: "user_002",
      name: "Sarah Johnson",
      email: "sarah.johnson@example.com",
      password: "hashed_password_456",
      emailVerified: true,
      identityVerified: false,
      teamId: "team_beta",
      fanSince: new Date("2021-11-08"),
      squadNumber: 23,
      username: "sarahj23",
      oauthProvider: "github",
      refreshTokenVersion: 2,
      createdAt: new Date("2021-11-08T09:15:00Z"),
      updatedAt: new Date("2024-12-19T16:45:00Z"),
      inviteCode: "SJ23NK7L",
      inviteCodeUsed: "CD5MN2QR",
      coin: "87"
    },
    {
      id: "user_003",
      name: "Michael Chen",
      email: "michael.chen@example.com",
      password: "hashed_password_789",
      emailVerified: false,
      identityVerified: true,
      teamId: "team_gamma",
      fanSince: new Date("2023-01-20"),
      squadNumber: 11,
      username: "mchen11",
      oauthProvider: "local",
      refreshTokenVersion: 1,
      createdAt: new Date("2023-01-20T13:22:00Z"),
      updatedAt: new Date("2024-12-18T11:30:00Z"),
      inviteCode: "MC11RP4T",
      inviteCodeUsed: "",
      coin: "21"
    },
    {
      id: "user_004",
      name: "Emma Wilson",
      email: "emma.wilson@example.com",
      password: "hashed_password_101",
      emailVerified: true,
      identityVerified: true,
      teamId: "team_alpha",
      fanSince: new Date("2020-06-12"),
      squadNumber: 19,
      username: "emmaw19",
      oauthProvider: "facebook",
      refreshTokenVersion: 3,
      createdAt: new Date("2020-06-12T08:45:00Z"),
      updatedAt: new Date("2024-12-21T10:15:00Z"),
      inviteCode: "EW19XY6Z",
      inviteCodeUsed: "FG7HJ9KL",
      coin: "32"
    },
    {
      id: "user_005",
      name: "David Rodriguez",
      email: "david.rodriguez@example.com",
      password: "hashed_password_202",
      emailVerified: true,
      identityVerified: false,
      teamId: "team_delta",
      fanSince: new Date("2023-07-30"),
      squadNumber: 5,
      username: "drodriguez5",
      oauthProvider: "google",
      refreshTokenVersion: 1,
      createdAt: new Date("2023-07-30T15:30:00Z"),
      updatedAt: new Date("2024-12-20T12:00:00Z"),
      inviteCode: "DR5MN8PQ",
      inviteCodeUsed: "ST1UV3WX",
      coin: "45"
    },
    {
      id: "user_006",
      name: "Lisa Thompson",
      email: "lisa.thompson@example.com",
      password: "hashed_password_303",
      emailVerified: false,
      identityVerified: false,
      teamId: "team_beta",
      fanSince: new Date("2024-02-14"),
      squadNumber: 33,
      username: "lisath33",
      oauthProvider: "local",
      refreshTokenVersion: 1,
      createdAt: new Date("2024-02-14T11:20:00Z"),
      updatedAt: new Date("2024-12-19T09:45:00Z"),
      inviteCode: "LT33BC4D",
      inviteCodeUsed: "",
      coin: "75"
    },
    {
      id: "user_007",
      name: "Alex Kim",
      email: "alex.kim@example.com",
      password: "hashed_password_404",
      emailVerified: true,
      identityVerified: true,
      teamId: "team_gamma",
      fanSince: new Date("2022-09-05"),
      squadNumber: 42,
      username: "alexkim42",
      oauthProvider: "github",
      refreshTokenVersion: 2,
      createdAt: new Date("2022-09-05T14:10:00Z"),
      updatedAt: new Date("2024-12-21T16:30:00Z"),
      inviteCode: "AK42EF7G",
      inviteCodeUsed: "HI9JK2LM",
      coin: "16"
    },
    {
      id: "user_008",
      name: "Maria Garcia",
      email: "maria.garcia@example.com",
      password: "hashed_password_505",
      emailVerified: true,
      identityVerified: true,
      teamId: "team_alpha",
      fanSince: new Date("2021-04-18"),
      squadNumber: 8,
      username: "mariagarcia8",
      oauthProvider: "google",
      refreshTokenVersion: 4,
      createdAt: new Date("2021-04-18T07:25:00Z"),
      updatedAt: new Date("2024-12-20T13:55:00Z"),
      inviteCode: "MG8NO5PQ",
      inviteCodeUsed: "RS6TU8VW",
      coin: "28"
    },
    {
      id: "user_009",
      name: "James Brown",
      email: "james.brown@example.com",
      password: "hashed_password_606",
      emailVerified: false,
      identityVerified: true,
      teamId: "team_delta",
      fanSince: new Date("2023-11-22"),
      squadNumber: 14,
      username: "jamesbrown14",
      oauthProvider: "local",
      refreshTokenVersion: 1,
      createdAt: new Date("2023-11-22T16:40:00Z"),
      updatedAt: new Date("2024-12-18T14:20:00Z"),
      inviteCode: "JB14XY9Z",
      inviteCodeUsed: "",
      coin: "32"
    },
    {
      id: "user_010",
      name: "Sophie Anderson",
      email: "sophie.anderson@example.com",
      password: "hashed_password_707",
      emailVerified: true,
      identityVerified: false,
      teamId: "team_beta",
      fanSince: new Date("2022-12-03"),
      squadNumber: 27,
      username: "sophieanderson27",
      oauthProvider: "facebook",
      refreshTokenVersion: 2,
      createdAt: new Date("2022-12-03T12:15:00Z"),
      updatedAt: new Date("2024-12-21T08:30:00Z"),
      inviteCode: "SA27AB1C",
      inviteCodeUsed: "DE4FG7HI",
      coin: "19"
    },
    {
      id: "user_011",
      name: "Sophia Anderson",
      email: "sophia.anderson@example.com",
      password: "hashed_password_707",
      emailVerified: true,
      identityVerified: false,
      teamId: "team_beta",
      fanSince: new Date("2022-12-03"),
      squadNumber: 27,
      username: "sophieanderson27",
      oauthProvider: "facebook",
      refreshTokenVersion: 2,
      createdAt: new Date("2022-12-03T12:15:00Z"),
      updatedAt: new Date("2024-12-21T08:30:00Z"),
      inviteCode: "SA27AB1C",
      inviteCodeUsed: "DE4FG7HI",
      coin: "19"
    }
  ];

  export const clubs: Club[] = [
    {
      id: "arsenal",
      name: "Arsenal",
      country: "England",
      league: "Premier League",
      primaryColor: "#DC0006",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/19/19.png",
      teamId1: "75dedcb6-6e19-4e7e-b324-d9b3f05be8a2",
      teamId2: "19",
      abbreviation: "ARS",
    },
    {
      id: "barcelona",
      name: "Barcelona",
      country: "Spain",
      league: "La Liga",
      primaryColor: "#670876",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/19/83.png",
      teamId1: "9ae986ee-5864-4e8c-a653-d9e0a4ee900b",
      teamId2: "83",
      abbreviation: "BAR"
    },
    {
      id: "chelsea",
      name: "Chelsea",
      country: "England",
      league: "Premier League",
      primaryColor: "#004495",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/18/18.png",
      teamId1: "7db63aea-e3e1-47db-b2c0-1ca8cce4901b",
      teamId2: "18",
      abbreviation: "CHE"
    },
    {
      id: "liverpool",
      name: "Liverpool",
      country: "England",
      league: "Premier League",
      primaryColor: "#C8102E",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/8/8.png",
      teamId1: "ac74b00c-12ff-4a30-a187-6b62fbe8b19e",
      teamId2: "8",
      abbreviation: "LIV"
    },
    {
      id: "manu",
      name: "Manchester United",
      country: "England",
      league: "Premier League",
      primaryColor: "#D1010D",
      secondaryColor: "#000000",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/14/14.png",
      teamId1: "33cd7d9e-e757-4838-b0bd-22efd47c06a8",
      teamId2: "14",
      abbreviation: "MUN"
    },
    {
      id: "mancity",
      name: "Manchester City",
      country: "England",
      league: "Premier League",
      primaryColor: "#6CABDD",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/9/9.png",
      teamId1: "fee84484-4fed-43c3-b92d-69431ac9b7a9",
      teamId2: "9",
      abbreviation: "MCI" 
    },
    {
      id: "realmadrid",
      name: "Real Madrid",
      country: "Spain",
      league: "La Liga",
      primaryColor: "#FBBC00",
      secondaryColor: "#000000",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/12/3468.png",
      teamId1: "5d931f5b-6d39-4e12-966b-ffed474f199e",
      teamId2: "3468",
      abbreviation: "RMA"
    },
    {
      id: "psg",
      name: "Paris Saint Germain",
      country: "France",
      league: "Ligue 1",
      primaryColor: "#E30613",
      secondaryColor: "#FFFFFF",
      crestUrl: "https://cdn.sportmonks.com/images/soccer/teams/21/85.png",
      teamId1: "a0d40eae-6f15-4f4e-9a3f-a36d09caf3cc",
      teamId2: "85",
      abbreviation: "PSG"
    }
  ];
 
  export const mockUserDetails: User = {
    id: "user_001",
    name: "John Smith",
    email: "john.smith@example.com",
    password: "hashed_password_123",
    emailVerified: true,
    identityVerified: true,
    teamId: "team_alpha",
    fanSince: new Date("2022-03-15"),
    squadNumber: 7,
    username: "johnsmith07",
    oauthProvider: "google",
    refreshTokenVersion: 1,
    createdAt: new Date("2022-03-15T10:30:00Z"),
    updatedAt: new Date("2024-12-20T14:22:00Z"),
    inviteCode: "JS7XM2K9",
    inviteCodeUsed: "AB3KL8NP",
    coin: "12",
    coinTransactions: [
      {
        id: "txn_001",
        userId: "user_001",
        type: "earned",
        amount: 50,
        description: "Daily login bonus",
        reference: "daily_login_2024_12_20",
        status: "completed",
        createdAt: new Date("2024-12-20T08:00:00Z"),
        updatedAt: new Date("2024-12-20T08:00:00Z")
      },
      {
        id: "txn_002",
        userId: "user_001",
        type: "spent",
        amount: -25,
        description: "Premium feature unlock",
        reference: "feature_premium_stats",
        status: "completed",
        createdAt: new Date("2024-12-19T14:30:00Z"),
        updatedAt: new Date("2024-12-19T14:30:00Z")
      },
      {
        id: "txn_003",
        userId: "user_001",
        type: "earned",
        amount: 100,
        description: "Referral bonus - Friend joined",
        reference: "invite_JS7XM2K9_user_045",
        status: "completed",
        createdAt: new Date("2024-12-18T16:45:00Z"),
        updatedAt: new Date("2024-12-18T16:45:00Z")
      },
      {
        id: "txn_004",
        userId: "user_001",
        type: "bonus",
        amount: 200,
        description: "Weekly challenge completion",
        reference: "challenge_week_51_2024",
        status: "completed",
        createdAt: new Date("2024-12-17T20:00:00Z"),
        updatedAt: new Date("2024-12-17T20:00:00Z")
      },
      {
        id: "txn_005",
        userId: "user_001",
        type: "spent",
        amount: -75,
        description: "Merchandise purchase",
        reference: "order_ORD789456",
        status: "completed",
        createdAt: new Date("2024-12-16T11:20:00Z"),
        updatedAt: new Date("2024-12-16T11:20:00Z")
      },
      {
        id: "txn_006",
        userId: "user_001",
        type: "earned",
        amount: 30,
        description: "Survey completion",
        reference: "survey_fan_experience_2024",
        status: "completed",
        createdAt: new Date("2024-12-15T13:15:00Z"),
        updatedAt: new Date("2024-12-15T13:15:00Z")
      },
      {
        id: "txn_007",
        userId: "user_001",
        type: "refund",
        amount: 50,
        description: "Event cancellation refund",
        reference: "event_cancelled_EVT123",
        status: "completed",
        createdAt: new Date("2024-12-14T09:30:00Z"),
        updatedAt: new Date("2024-12-14T09:30:00Z")
      },
      {
        id: "txn_008",
        userId: "user_001",
        type: "earned",
        amount: 25,
        description: "Social media share bonus",
        reference: "share_instagram_post_456",
        status: "completed",
        createdAt: new Date("2024-12-13T18:45:00Z"),
        updatedAt: new Date("2024-12-13T18:45:00Z")
      },
      {
        id: "txn_009",
        userId: "user_001",
        type: "spent",
        amount: -40,
        description: "Digital wallpaper pack",
        reference: "digital_pack_winter_2024",
        status: "completed",
        createdAt: new Date("2024-12-12T15:20:00Z"),
        updatedAt: new Date("2024-12-12T15:20:00Z")
      },
      {
        id: "txn_010",
        userId: "user_001",
        type: "spent",
        amount: 80,
        description: "Contest participation reward",
        reference: "contest_photo_december",
        status: "pending",
        createdAt: new Date("2024-12-11T12:00:00Z"),
        updatedAt: new Date("2024-12-11T12:00:00Z")
      },
      {
        id: "txn_011",
        userId: "user_001",
        type: "spent",
        amount: 80,
        description: "Contest participation reward",
        reference: "contest_photo_december",
        status: "pending",
        createdAt: new Date("2024-12-11T12:00:00Z"),
        updatedAt: new Date("2024-12-11T12:00:00Z")
      }
    ],
    invitedUsers: [
      {
        id: "invite_001",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_045",
        usedByName: "Sarah Johnson",
        usedByEmail: "sarah.johnson@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-12-18T16:45:00Z"),
        createdAt: new Date("2024-12-18T16:45:00Z")
      },
      {
        id: "invite_002",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_067",
        usedByName: "Mike Chen",
        usedByEmail: "mike.chen@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-12-10T14:20:00Z"),
        createdAt: new Date("2024-12-10T14:20:00Z")
      },
      {
        id: "invite_003",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_089",
        usedByName: "Emma Wilson",
        usedByEmail: "emma.wilson@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-12-05T09:15:00Z"),
        createdAt: new Date("2024-12-05T09:15:00Z")
      },
      {
        id: "invite_004",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_112",
        usedByName: "David Rodriguez",
        usedByEmail: "david.rodriguez@example.com",
        rewardGiven: 100,
        status: "inactive",
        usedAt: new Date("2024-11-28T11:30:00Z"),
        createdAt: new Date("2024-11-28T11:30:00Z")
      },
      {
        id: "invite_005",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_134",
        usedByName: "Lisa Anderson",
        usedByEmail: "lisa.anderson@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-11-22T16:45:00Z"),
        createdAt: new Date("2024-11-22T16:45:00Z")
      },
      {
        id: "invite_006",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_156",
        usedByName: "Alex Thompson",
        usedByEmail: "alex.thompson@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-11-15T13:20:00Z"),
        createdAt: new Date("2024-11-15T13:20:00Z")
      },
      {
        id: "invite_007",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_178",
        usedByName: "Jennifer Lee",
        usedByEmail: "jennifer.lee@example.com",
        rewardGiven: 100,
        status: "banned",
        usedAt: new Date("2024-11-08T10:45:00Z"),
        createdAt: new Date("2024-11-08T10:45:00Z")
      },
      {
        id: "invite_008",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_201",
        usedByName: "Ryan Martinez",
        usedByEmail: "ryan.martinez@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-11-01T15:30:00Z"),
        createdAt: new Date("2024-11-01T15:30:00Z")
      },
      {
        id: "invite_009",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_223",
        usedByName: "Amanda Davis",
        usedByEmail: "amanda.davis@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-10-25T12:15:00Z"),
        createdAt: new Date("2024-10-25T12:15:00Z")
      },
      {
        id: "invite_010",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_245",
        usedByName: "Kevin Brown",
        usedByEmail: "kevin.brown@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-10-18T14:45:00Z"),
        createdAt: new Date("2024-10-18T14:45:00Z")
      },
      {
        id: "invite_011",
        inviteCode: "JS7XM2K9",
        invitedBy: "user_001",
        invitedByName: "John Smith",
        usedBy: "user_245",
        usedByName: "Kevin Brown",
        usedByEmail: "kevin.brown@example.com",
        rewardGiven: 100,
        status: "active",
        usedAt: new Date("2024-10-18T14:45:00Z"),
        createdAt: new Date("2024-10-18T14:45:00Z")
      }
    ]
  }

  export const mockFixtures = [
    // Arsenal vs Chelsea - Premier League Derby
    {
      matchId: "EPL_001_2025",
      fixtureId: "FXT_EPL_001_2025",
      homeTeamId: "ARS",
      homeTeamName: "Arsenal",
      homeTeamImageUrl: "https://logos.soccerdata.com/arsenal.png",
      awayTeamId: "CHE",
      awayTeamName: "Chelsea",
      awayTeamImageUrl: "https://logos.soccerdata.com/chelsea.png",
      matchStartTime: new Date("2025-06-21T17:30:00Z"),
      matchState: "live",
      homeScore: 2,
      awayScore: 1,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-21T18:45:00Z"),
      createdAt: new Date("2025-06-15T09:00:00Z")
    },
    // Manchester United vs Liverpool - Classic Rivalry
    {
      matchId: "EPL_002_2025",
      fixtureId: "FXT_EPL_002_2025",
      homeTeamId: "MAN_UTD",
      homeTeamName: "Manchester United",
      homeTeamImageUrl: "https://logos.soccerdata.com/man_utd.png",
      awayTeamId: "LIV",
      awayTeamName: "Liverpool",
      awayTeamImageUrl: "https://logos.soccerdata.com/liverpool.png",
      matchStartTime: new Date("2025-06-22T15:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-20T10:30:00Z"),
      createdAt: new Date("2025-06-15T09:00:00Z")
    },
    // Manchester City vs Tottenham
    {
      matchId: "EPL_003_2025",
      fixtureId: "FXT_EPL_003_2025",
      homeTeamId: "MAN_CITY",
      homeTeamName: "Manchester City",
      homeTeamImageUrl: "https://logos.soccerdata.com/man_city.png",
      awayTeamId: "TOT",
      awayTeamName: "Tottenham Hotspur",
      awayTeamImageUrl: "https://logos.soccerdata.com/tottenham.png",
      matchStartTime: new Date("2025-06-19T20:00:00Z"),
      matchState: "finished",
      homeScore: 4,
      awayScore: 1,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-19T22:00:00Z"),
      createdAt: new Date("2025-06-14T09:00:00Z")
    },
    // El Clasico - Real Madrid vs Barcelona
    {
      matchId: "LALIGA_001_2025",
      fixtureId: "FXT_LALIGA_001_2025",
      homeTeamId: "RMA",
      homeTeamName: "Real Madrid",
      homeTeamImageUrl: "https://logos.soccerdata.com/real_madrid.png",
      awayTeamId: "FCB",
      awayTeamName: "FC Barcelona",
      awayTeamImageUrl: "https://logos.soccerdata.com/barcelona.png",
      matchStartTime: new Date("2025-06-23T19:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "La Liga",
      leagueImageUrl: "https://logos.soccerdata.com/laliga.png",
      lastUpdated: new Date("2025-06-20T14:20:00Z"),
      createdAt: new Date("2025-06-16T11:00:00Z")
    },
    // Barcelona vs Atletico Madrid
    {
      matchId: "LALIGA_002_2025",
      fixtureId: "FXT_LALIGA_002_2025",
      homeTeamId: "FCB",
      homeTeamName: "FC Barcelona",
      homeTeamImageUrl: "https://logos.soccerdata.com/barcelona.png",
      awayTeamId: "ATM",
      awayTeamName: "Atletico Madrid",
      awayTeamImageUrl: "https://logos.soccerdata.com/atletico_madrid.png",
      matchStartTime: new Date("2025-06-18T18:30:00Z"),
      matchState: "finished",
      homeScore: 3,
      awayScore: 2,
      leagueName: "La Liga",
      leagueImageUrl: "https://logos.soccerdata.com/laliga.png",
      lastUpdated: new Date("2025-06-18T20:30:00Z"),
      createdAt: new Date("2025-06-13T10:00:00Z")
    },
    // PSG vs Olympique Marseille - Le Classique
    {
      matchId: "LIGUE1_001_2025",
      fixtureId: "FXT_LIGUE1_001_2025",
      homeTeamId: "PSG",
      homeTeamName: "Paris Saint-Germain",
      homeTeamImageUrl: "https://logos.soccerdata.com/psg.png",
      awayTeamId: "OLY",
      awayTeamName: "Olympique Marseille",
      awayTeamImageUrl: "https://logos.soccerdata.com/marseille.png",
      matchStartTime: new Date("2025-06-20T20:00:00Z"),
      matchState: "finished",
      homeScore: 2,
      awayScore: 0,
      leagueName: "Ligue 1",
      leagueImageUrl: "https://logos.soccerdata.com/ligue1.png",
      lastUpdated: new Date("2025-06-20T22:00:00Z"),
      createdAt: new Date("2025-06-15T13:45:00Z")
    },
    // Champions League - Real Madrid vs Manchester City
    {
      matchId: "CL_001_2025",
      fixtureId: "FXT_CL_001_2025",
      homeTeamId: "RMA",
      homeTeamName: "Real Madrid",
      homeTeamImageUrl: "https://logos.soccerdata.com/real_madrid.png",
      awayTeamId: "MAN_CITY",
      awayTeamName: "Manchester City",
      awayTeamImageUrl: "https://logos.soccerdata.com/man_city.png",
      matchStartTime: new Date("2025-06-25T19:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "UEFA Champions League",
      leagueImageUrl: "https://logos.soccerdata.com/champions_league.png",
      lastUpdated: new Date("2025-06-20T11:00:00Z"),
      createdAt: new Date("2025-06-18T14:20:00Z")
    },
    // Champions League - PSG vs Arsenal
    {
      matchId: "CL_002_2025",
      fixtureId: "FXT_CL_002_2025",
      homeTeamId: "PSG",
      homeTeamName: "Paris Saint-Germain",
      homeTeamImageUrl: "https://logos.soccerdata.com/psg.png",
      awayTeamId: "ARS",
      awayTeamName: "Arsenal",
      awayTeamImageUrl: "https://logos.soccerdata.com/arsenal.png",
      matchStartTime: new Date("2025-06-26T19:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "UEFA Champions League",
      leagueImageUrl: "https://logos.soccerdata.com/champions_league.png",
      lastUpdated: new Date("2025-06-20T12:15:00Z"),
      createdAt: new Date("2025-06-18T15:30:00Z")
    },
    // Premier League - Liverpool vs Newcastle
    {
      matchId: "EPL_004_2025",
      fixtureId: "FXT_EPL_004_2025",
      homeTeamId: "LIV",
      homeTeamName: "Liverpool",
      homeTeamImageUrl: "https://logos.soccerdata.com/liverpool.png",
      awayTeamId: "NEW",
      awayTeamName: "Newcastle United",
      awayTeamImageUrl: "https://logos.soccerdata.com/newcastle.png",
      matchStartTime: new Date("2025-06-22T12:30:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-20T09:45:00Z"),
      createdAt: new Date("2025-06-16T08:30:00Z")
    },
    // Premier League - Chelsea vs Brighton
    {
      matchId: "EPL_005_2025",
      fixtureId: "FXT_EPL_005_2025",
      homeTeamId: "CHE",
      homeTeamName: "Chelsea",
      homeTeamImageUrl: "https://logos.soccerdata.com/chelsea.png",
      awayTeamId: "BRI",
      awayTeamName: "Brighton & Hove Albion",
      awayTeamImageUrl: "https://logos.soccerdata.com/brighton.png",
      matchStartTime: new Date("2025-06-17T16:00:00Z"),
      matchState: "finished",
      homeScore: 2,
      awayScore: 1,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-17T18:00:00Z"),
      createdAt: new Date("2025-06-12T10:15:00Z")
    },
    // La Liga - Real Madrid vs Valencia
    {
      matchId: "LALIGA_003_2025",
      fixtureId: "FXT_LALIGA_003_2025",
      homeTeamId: "RMA",
      homeTeamName: "Real Madrid",
      homeTeamImageUrl: "https://logos.soccerdata.com/real_madrid.png",
      awayTeamId: "VAL",
      awayTeamName: "Valencia",
      awayTeamImageUrl: "https://logos.soccerdata.com/valencia.png",
      matchStartTime: new Date("2025-06-21T16:30:00Z"),
      matchState: "live",
      homeScore: 1,
      awayScore: 0,
      leagueName: "La Liga",
      leagueImageUrl: "https://logos.soccerdata.com/laliga.png",
      lastUpdated: new Date("2025-06-21T17:15:00Z"),
      createdAt: new Date("2025-06-15T11:20:00Z")
    },
    // Premier League - Manchester United vs West Ham
    {
      matchId: "EPL_006_2025",
      fixtureId: "FXT_EPL_006_2025",
      homeTeamId: "MAN_UTD",
      homeTeamName: "Manchester United",
      homeTeamImageUrl: "https://logos.soccerdata.com/man_utd.png",
      awayTeamId: "WHU",
      awayTeamName: "West Ham United",
      awayTeamImageUrl: "https://logos.soccerdata.com/west_ham.png",
      matchStartTime: new Date("2025-06-19T17:00:00Z"),
      matchState: "finished",
      homeScore: 3,
      awayScore: 1,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-19T19:00:00Z"),
      createdAt: new Date("2025-06-14T15:30:00Z")
    },
    // Ligue 1 - PSG vs Lyon
    {
      matchId: "LIGUE1_002_2025",
      fixtureId: "FXT_LIGUE1_002_2025",
      homeTeamId: "PSG",
      homeTeamName: "Paris Saint-Germain",
      homeTeamImageUrl: "https://logos.soccerdata.com/psg.png",
      awayTeamId: "OL",
      awayTeamName: "Olympique Lyonnais",
      awayTeamImageUrl: "https://logos.soccerdata.com/lyon.png",
      matchStartTime: new Date("2025-06-24T19:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "Ligue 1",
      leagueImageUrl: "https://logos.soccerdata.com/ligue1.png",
      lastUpdated: new Date("2025-06-20T13:15:00Z"),
      createdAt: new Date("2025-06-18T16:45:00Z")
    },
    // Premier League - Arsenal vs Aston Villa
    {
      matchId: "EPL_007_2025",
      fixtureId: "FXT_EPL_007_2025",
      homeTeamId: "ARS",
      homeTeamName: "Arsenal",
      homeTeamImageUrl: "https://logos.soccerdata.com/arsenal.png",
      awayTeamId: "AVL",
      awayTeamName: "Aston Villa",
      awayTeamImageUrl: "https://logos.soccerdata.com/aston_villa.png",
      matchStartTime: new Date("2025-06-24T20:00:00Z"),
      matchState: "not_started",
      homeScore: 0,
      awayScore: 0,
      leagueName: "Premier League",
      leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
      lastUpdated: new Date("2025-06-20T08:00:00Z"),
      createdAt: new Date("2025-06-17T12:00:00Z")
    }
  ]

  export const mockFixtureDetails =   {
    matchId: "EPL_001_2025",
    fixtureId: "FXT_EPL_001_2025",
    homeTeamId: "ARS",
    homeTeamName: "Arsenal",
    homeTeamImageUrl: "https://logos.soccerdata.com/arsenal.png",
    awayTeamId: "CHE",
    awayTeamName: "Chelsea",
    awayTeamImageUrl: "https://logos.soccerdata.com/chelsea.png",
    matchStartTime: new Date("2025-06-21T17:30:00Z"),
    matchState: "live",
    homeScore: 2,
    awayScore: 1,
    leagueName: "Premier League",
    leagueImageUrl: "https://logos.soccerdata.com/premier_league.png",
    lastUpdated: new Date("2025-06-21T18:45:00Z"),
    createdAt: new Date("2025-06-15T09:00:00Z"),
    chatList: mockUsers
  }